/**
 * Playwright spec: Cleanup
 * Generated by Bug0 backup from project "TaskFlow".
 * Do not edit manually if re-backing up; changes may be overwritten.
 */

import { test, expect } from '@playwright/test';

test.describe("Cleanup", () => {
  test.skip("Delete all tasks", { timeout: 300000 }, async ({ page }) => {
  // Click the "Delete" button on all the task card one after the other
  await expect(page.getByRole('generic')).toContainText("confirm there's no task card on the page", { timeout: 10000 });
  });
});
