/**
 * Playwright spec: Custom Script
 * Generated by Bug0 backup from project "TaskFlow".
 * Do not edit manually if re-backing up; changes may be overwritten.
 */

import { test, expect } from '@playwright/test';

test.describe("Custom Script", () => {
  test.skip("Add Task", { timeout: 300000 }, async ({ page }) => {
  // Module
  await page.getByRole('button', { name: 'Add New Task' }).click();
  await page.getByRole('textbox', { name: 'Task Title *' }).fill('Buy Milk');
  await page.getByRole('textbox', { name: 'Description (optional)' }).fill('Buy milk in the evening time after work');
  await page.getByRole('button', { name: 'Create Task' }).click();
  await expect(page.getByRole('main')).toContainText('Buy Milk');
  });
});
