/**
 * Playwright spec: Task CRUD
 * Generated by Bug0 backup from project "TaskFlow".
 * Do not edit manually if re-backing up; changes may be overwritten.
 */

import { test, expect } from '@playwright/test';

test.describe("Task CRUD", () => {
  test.skip("Add Task", { timeout: 300000 }, async ({ page }) => {
  // Click "Create Task"
  // Type "Buy Bread {{run.shortid}}" into "Task Title"
  // Type "Go to the store in the evening and buy bread" into "Description"
  // Click "Create Task"
  await page.waitForLoadState('Task created');
  // module from add task
  });
  test.skip("Mark Task as Completed", { timeout: 300000 }, async ({ page }) => {
  // Click "Add New Task"
  // Type "Task {{run.shortid}}" into "Task Title"
  // Type "Description {{run.shortid}}" into "Description"
  // Click "Add Task"
  await page.waitForLoadState('Task added successfully');
  // Click "Complete"
  await page.waitForLoadState('Task marked as completed');
  // module from mark task a completed
  });
});
